# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
